### PR TITLE
fix 383

### PR DESCRIPTION
**Pull request by dsyme**
Tentative fix for #383 

The docs for FSharp.Core are also updated

### CODE REVIEW

**Comment by dungpa** [comment]
I thought about this again. It's unreasonable to expect cracking multiple versions of FSharp.Core inside FCS. I will do FSharp.Core cracking from VFPT as discussed.

I tested this PR on VFPT, it seems to work fine. 

Could you publish a non-beta NuGet package support F# 4.0? This branch is already quite stable and current FCS beta causes all consumers (Fantomas, FSharpLint.Core, FSharpVSPowerTools.Core) to be beta as well.

**Comment by rneatherway** [comment]
@dungpa will you ship with one version of FCS (i.e. the F# 4.0 version) for installation into all VS versions? I'm wondering if I can do the same for FsAutoComplete.

**Comment by dungpa** [comment]
> will you ship with one version of FCS (i.e. the F# 4.0 version) for installation into all VS versions? 

Yes, that's my plan. Based on VS versions, we will crack compiler arguments to provide suitable FSharp.Core versions for `GetCheckerOptionsFromScript`.

**Comment by rneatherway** [comment]
OK, that makes sense. That VS context is useful, I guess I will just default to FSharp.Core 4.4.0.0.

**Comment by 7sharp9** [comment]
Can you post details of the fix for the other editors?

**Comment by rneatherway** [comment]
@dungpa/@dsyme: just to clarify, is there any downside to using FSharp.Core 4.4.0.0 for scripts originally developed against older versions of FSharp.Core? Also, what would the effect be of deploying a version of FsAutoComplete on a machine without F# 4.0 installed? I assume it would work OK except for this issue with returning FSHarp.Core 4.4.0.0, which wouldn't exist in that case?

**Comment by dsyme** [comment]
@rneatherway Don't forget the FSharp.Core used by the host process (if any) will be preferred. So the FSharp.Core used by FsAutoComplete.exe will be preferred.

If your host process doesn't reference FSharp.Core then the downside is that F# scripts won't typecheck correctly at all unless you have FSharp.Core 4.4.0.0 (and sigdata/optdata) available on your system.

**Comment by rneatherway** [comment]
OK, so it sounds like it is completely safe for me to update to FCS 1.4.0.X, thanks!

As I'm about to also ask if @dungpa can link to his implementation, I do wonder if this could be a utility function in FCS after all. I assume we want to probe for the latest version of FSharp.Core available on the system and offer that?

**Comment by dsyme** [comment]
@dungpa FCS 1.4.0.2 released as non-alpha

**Comment by dungpa** [comment]
@dsyme Thanks.

**Pull request merged**
