### PR TITLE
use .net core sdk preview1 in appveyor

### PR DESCRIPTION
**Pull request by enricosada**
- use .net core sdk preview1 in appveyor (by default is installed preview2)
- pin version of fsharp.core package to one who support .net core rc2 ( using `-*` resolve latest, with .net core 1.0 rtm)

### CODE REVIEW

**Comment by enricosada** [comment]
i am checking failure

**Comment by enricosada** [comment]
ah got it, the .net core rtm changes are merged.
i'll update to `preview2` so /cc @dsyme

**Comment by enricosada** [comment]
ok @dsyme , updated to .net core sdk `preview2`.
The errors i see i think are not about new preview2 or .net core rtm. 
i need some help about that,

**Comment by enricosada** [comment]
i remove the limit on error count:

Some interesting errors

```
E:\github\FSharp.Compiler.Service\src\fsharp\TypeChecker.fs(9264,75): error FS0001: This expression was expected to 
have type    'MethInfo'    but here has type    'ILMethodSpec'
E:\github\FSharp.Compiler.Service\src\fsharp\TypeChecker.fs(9271,13): error FS0193: Type constraint mismatch. The type 
    'ILMethodSpec'    is not compatible with type    'MemberFlags'

E:\github\FSharp.Compiler.Service\src\fsharp\TypeChecker.fs(9272,30): error FS0001: This expression was expected to 
have type    'TType'    but here has type    'ILType'
E:\github\FSharp.Compiler.Service\src\fsharp\TypeChecker.fs(9279,82): error FS0001: This expression was expected to 
have type    'TType'    but here has type    'ILType'
```

**Comment by dsyme** [comment]
Very odd, I don't see those errors on a clean build of "master"

**Comment by dsyme** [comment]
Sorry, project.json was out of date

See https://github.com/fsharp/FSharp.Compiler.Service/commit/2aac1b176294fe12e0b17d4bb6c3e1dbd62da962.  Not sure if this is all the files to add to project.json

**Comment by enricosada** [comment]
i'll add that commit

**Comment by enricosada** [comment]
one error only

```
E:\github\FSharp.Compiler.Service\src\fsharp\vs\Exprs.fs(938,20): error FS1182: The value 'isRec' is unused
```

nice :dancer:

**Comment by enricosada** [comment]
FCS ok, projectcracker fail. i'll check

**Comment by enricosada** [comment]
ok now only the test fails. i dont know why, same error, 

```
122) Error : Tests.Service.ProjectAnalysisTests.Test symbol uses of properties with both getters and setters
System.TypeInitializationException : The type initializer for '<StartupCode$FSharp-Compiler-Service-Tests-netcore>.$Test
s.Service.ProjectAnalysisTests' threw an exception.
  ----> Microsoft.FSharp.Compiler.ErrorLogger+ReportedError : The type 'UIntPtr' is required here and is unavailable. Yo
u must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
```

maybe it's thinking is fulldesktop instead of netcore when resolve assemblies? take note how with preview2 there are `netstandard1.6` and `netcoreapp1.0` is used more (previuosly `netstandard1.5` was used both lib and console)

**Comment by dsyme** [comment]
I'll merge for now and then let's continue to try to get the netcore version to pass.  Otherwise I guess we should disable it from CI

**Comment by enricosada** [comment]
well package are ok, maybe @7sharp9 can try use it with FSAC

**Pull request merged**
