### PR TITLE
WIP: Make CoreCLR work

### PR DESCRIPTION
**Pull request by matthid**
Don't merge, I have no Idea what I'm doing :)
See https://github.com/fsharp/FAKE/pull/1281

### CODE REVIEW

**Comment by dsyme** [comment]
@ncave - Could you take a look please?

**Comment by matthid** [comment]
The last commit is not needed... I think it will come with the next visualfsharp merge:
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/absil/ilreflect.fs#L1184
vs
https://github.com/Microsoft/visualfsharp/blob/29354edbf0cfb67bc59d9b3d1aaac114bca43ef5/src/absil/ilreflect.fs#L1177

Will clean this up later.

**Comment by ncave** [comment]
@KevinRansom @dsyme As this commit makes changes in reshapedmsbuild.fs, and RTM is just around the corner, what is the longer term plan, is reshapedmsbuild going to go away and be replaces with msbuild references?

**Comment by dsyme** [comment]
@matthid We've now integrated all the changes from visualfsharp.  Could you merge with master and update the PR please?  Thanks

**Comment by matthid** [comment]
I guess you were faster :)

**Pull request closed without merging**
