### PR TITLE
Fixed path to Razor

### PR DESCRIPTION
**Pull request by sergey-tihon**
@rneatherway I do not have clone with working version =(
This PR should fix issues with path to Razor https://github.com/fsharp/FSharp.Compiler.Service/pull/349

But on my machine I have this error
https://github.com/tpetricek/FSharp.Formatting/issues/272

### CODE REVIEW

**Comment by rneatherway** [comment]
I also have the same error. Did you try referencing the VSPowerTools as the suggested? https://github.com/fsprojects/ProjectScaffold/commit/29be5a01404a755755c90f1812c1c6b456cdf4d9

(I don't have Windows access right now to try)

**Comment by sergey-tihon** [comment]
You are right - it works now.

**Comment by rneatherway** [comment]
I plan to test and merge this tonight.

**Comment by rneatherway** [comment]
Works for me, thanks.

**Pull request merged**
