### PR TITLE
[WIP] Build on upcoming Mono version (Mono 5)

### PR DESCRIPTION
**Pull request by sergey-tihon**
Do not merge this PR, the only goal of this PR is to verify if this repo can be compiled on Mono 5

### CODE REVIEW

**Comment by dsyme** [comment]
I'd be happy to have CI against "beta" and "nightly"!

**Comment by sergey-tihon** [comment]
What build matrix you would like to have?
Something like this one?


| Mono | Linux | MacOS |
|-------|-------|---------|
| 4.4.2 | ✅  | exclude |
| 4.8.0 | ✅ |  exclude |
| `latest` | ✅ | ✅ |
| `beta` | ✅ | ✅ |
| `nighty` | allow_failures | allow_failures |

**Comment by dsyme** [comment]
Error on linux nightly

> /home/travis/build/fsharp/FSharp.Compiler.Service/packages/FSharp.Compiler.Tools/tools/Microsoft.FSharp.Targets(125,13): error MSB4131: The "ResourceFilesWithManifestResourceNames" parameter is not supported by the "CreateFSharpManifestResourceName" task. Verify the parameter exists on the task, and it is a gettable public instance property. [/home/travis/build/fsharp/FSharp.Compiler.Service/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]

@nosami have we seen this before?

**Comment by dsyme** [comment]
@sergey-tihon That looks about right.  We don't really need to exclude "macOS" on older MOno - we only did that because travis macOS was flaky for a while

**Comment by dsyme** [comment]
5 test errors on macOS beta:
```
1) Test Error : FSharp.Compiler.Service.Tests.FscTests.1. PEVerifier sanity check

   FSharp.Compiler.Service.Tests.FscTests+VerificationException : Verification of '/Users/travis/build/fsharp/FSharp.Compiler.Service/bin/v4.5/FSharp.Core.dll' failed with code 134, message <<<mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)



>>>

  at FSharp.Compiler.Service.Tests.FscTests+PEVerifier.Verify (System.String assemblyPath) [0x00111] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.1. PEVerifier sanity check () [0x0001e] in <5913096c85c5f7fea74503836c091359>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b697cffb61b74023aa9c587e6c49beb3>:0 



2) Test Error : FSharp.Compiler.Service.Tests.FscTests.2. Simple FSC library test

   FSharp.Compiler.Service.Tests.FscTests+VerificationException : Verification of '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/test1565288575/Foo.dll' failed with code 134, message <<<mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)



>>>

  at FSharp.Compiler.Service.Tests.FscTests+PEVerifier.Verify (System.String assemblyPath) [0x00111] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.compileAndVerify (System.Boolean isDll, FSharp.Compiler.Service.Tests.FscTests+DebugMode debugMode, System.String assemblyName, System.String ext, System.String code, Microsoft.FSharp.Collections.FSharpList`1[T] dependencies) [0x0001a] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.2. Simple FSC library test () [0x0001b] in <5913096c85c5f7fea74503836c091359>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b697cffb61b74023aa9c587e6c49beb3>:0 



3) Test Error : FSharp.Compiler.Service.Tests.FscTests.3. Simple FSC executable test

   FSharp.Compiler.Service.Tests.FscTests+VerificationException : Verification of '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/test-988165832/Bar.exe' failed with code 134, message <<<mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)



>>>

  at FSharp.Compiler.Service.Tests.FscTests+PEVerifier.Verify (System.String assemblyPath) [0x00111] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.compileAndVerify (System.Boolean isDll, FSharp.Compiler.Service.Tests.FscTests+DebugMode debugMode, System.String assemblyName, System.String ext, System.String code, Microsoft.FSharp.Collections.FSharpList`1[T] dependencies) [0x0001a] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.3. Simple FSC executable test () [0x0001b] in <5913096c85c5f7fea74503836c091359>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b697cffb61b74023aa9c587e6c49beb3>:0 



4) Test Error : FSharp.Compiler.Service.Tests.FscTests.4. Compile from simple AST

   FSharp.Compiler.Service.Tests.FscTests+VerificationException : Verification of '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/test-1953860418/foo.dll' failed with code 134, message <<<mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)



>>>

  at FSharp.Compiler.Service.Tests.FscTests+PEVerifier.Verify (System.String assemblyPath) [0x00111] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.compileAndVerifyAst (System.String name, Microsoft.FSharp.Collections.FSharpList`1[T] ast, Microsoft.FSharp.Collections.FSharpList`1[T] references) [0x00180] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.4. Compile from simple AST () [0x00021] in <5913096c85c5f7fea74503836c091359>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b697cffb61b74023aa9c587e6c49beb3>:0 



5) Test Error : FSharp.Compiler.Service.Tests.FscTests.5. Compile from AST with explicit assembly reference

   FSharp.Compiler.Service.Tests.FscTests+VerificationException : Verification of '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/test2044757591/bar.dll' failed with code 134, message <<<mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)



>>>

  at FSharp.Compiler.Service.Tests.FscTests+PEVerifier.Verify (System.String assemblyPath) [0x00111] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.compileAndVerifyAst (System.String name, Microsoft.FSharp.Collections.FSharpList`1[T] ast, Microsoft.FSharp.Collections.FSharpList`1[T] references) [0x00180] in <5913096c85c5f7fea74503836c091359>:0 

  at FSharp.Compiler.Service.Tests.FscTests.5. Compile from AST with explicit assembly reference () [0x0003c] in <5913096c85c5f7fea74503836c091359>:0 

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <b697cffb61b74023aa9c587e6c49beb3>:0 


```

**Comment by nosami** [comment]
> @nosami have we seen this before?
It's possibly the same issue as this https://bugzilla.xamarin.com/show_bug.cgi?id=53195

**Comment by nosami** [comment]
I discovered yesterday after speaking with @directhex that this patch isn't in the linux build, but is in OSX

```fsharp
commit 8f93ad340dc81a23155e68c79a5c3eab53b6eeb5
Author: Ankit Jain <ankit.jain@xamarin.com>
Date:   Sat Apr 15 04:17:18 2017 -0400

    [msbuild] Fix test for is-running-on-xbuild

diff --git a/src/fsharp/FSharp.Build/Microsoft.FSharp.targets b/src/fsharp/FSharp.Build/Microsoft.FSharp.targets
index ec28077d..10840ada 100644
--- a/src/fsharp/FSharp.Build/Microsoft.FSharp.targets
+++ b/src/fsharp/FSharp.Build/Microsoft.FSharp.targets
@@ -66,7 +66,7 @@ this file.
 
     <PropertyGroup>
         <UsingXBuild>false</UsingXBuild>
-        <UsingXBuild Condition="$(MSBuildExtensionsPath32.Contains('xbuild'))">true</UsingXBuild>
+        <UsingXBuild Condition="'$(MSBuildAssemblyVersion)' == ''">true</UsingXBuild>
     </PropertyGroup>
 
     <Target
```

Workaround would probably to use `xbuild` instead of `msbuild`

**Comment by nosami** [comment]
```
14:33 $ peverify /Users/jason/src/FSharp.Compiler.Service/bin/v4.5/FSharp.Core.dll
mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)
Abort trap: 6
```
:(

**Comment by nosami** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=56177

**Comment by nosami** [comment]
@dsyme Do you happen to know if peverify from the .net SDK is managed code? Could we use that instead?

**Comment by dsyme** [comment]
@nosami Just disable those tests on macOS (and Linux if needed)  We run peverify on Windows and that is enough since the binary being verified is the same

**Comment by dsyme** [comment]
@with "Mono nightly" passing on Linux we should probably get that in the bank?  i.e. activate it in CI

**Comment by sergey-tihon** [comment]
@dsyme done

**Comment by dsyme** [comment]
@sergey-tihon Current status is this 

image

**Comment by sergey-tihon** [comment]
Sorry, my typo - fixed now


note, this is strange but mono latest on osx is still 4.8.1
so it should fail as well as beta

**Comment by sergey-tihon** [comment]
ILVerify - a standalone, cross platform, open-source tool that is capable of verifying MSIL code

https://twitter.com/gregkalapos/status/864189612503203840
https://github.com/dotnet/corert/tree/master/src/ILVerify

**Comment by nosami** [comment]
> ILVerify - a standalone, cross platform, open-source tool that is capable of verifying MSIL code
Cool! `peverify` was also just fixed in Mono 5.0 https://github.com/mono/mono/pull/4885

**Comment by dsyme** [comment]
Closing old PR

**Pull request closed without merging**
