### PR TITLE
Perform project cracking out of process

### PR DESCRIPTION
**Pull request by rneatherway**
References: #371, #354, #342, #337.

I've exposed the logging a bit more easily as when using this it is really important to be able to get feedback from users as to why it has broken again on their system.

This causes the project options tests for type providers to fail, but everything else is working. I'd appreciate some help if there is any magic I'm missing here, like if the new assembly needs a property set or something. (/cc @dsyme)

Example:

```
***** FSharp.Compiler.Service.Tests.ProjectAnalysisTests.Test Project25 whole project errors
[|startup (1,1)-(1,81) parameter warning Referenced assembly '/home/robin/dev/other/FSharp.Compiler.Service/tests/service/FSharp.Data.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found;
  /tmp/tmp56ff41d1.fs (4,16)-(4,27) typecheck error The type 'XmlProvider' is not defined;
  /tmp/tmp56ff41d1.fs (4,16)-(4,27) typecheck error The type 'XmlProvider' is not defined;
  /tmp/tmp56ff41d1.fs (5,17)-(5,26) typecheck error The field, constructor or member 'GetSample' is not defined;
  /tmp/tmp56ff41d1.fs (10,9)-(10,20) typecheck error The value or constructor 'XmlProvider' is not defined|]
```

Once that is fixed, I will do some tidying as below:

Todo:
- [x] Remove ProjectCrackerReader, used for testing prior to hooking up to FCS
- [x] Remove FCS references of MSBuild v12 and FSharpProjectFileInfo from service.fs
- [x] Change tests to use GetProjectOptionsFromProjectFile

### CODE REVIEW

**Comment by 7sharp9** [comment]
Are you adding the `mono` prefix when starting the process?

**Comment by rneatherway** [comment]
No, mono's StartProcess does that automatically if the target is a CLR executable.

**Comment by dsyme** [comment]
I couldn't immediately spot why that type provider DLL would be causing problems given your changes - nothing's really changed unless the actually options cracked have changed (e.g. the FSHarp.Core being chosen has changed - that could cause the error you're seeing).  Are tests running clean without your changes?  thanks

**Comment by rneatherway** [comment]
@dsyme yes, the tests run clean without the changes. I'll have to get logs for those projects before and after for comparison.

**Comment by rneatherway** [comment]
@dsyme I'd like to ask a quick bit of advice. I have this all working quite nicely, but FSharp.Core is proving to be a problem. This new `ProjectCracker.exe` needs to be in the same directory as `FSharp.Compiler.Service.dll` so that `FSharp.Compiler.Service.dll` can access the record type that is used to serialize the results. However that means there can't be an FSharp.Core in that directory (because it is the choice of the consumer of FCS what FSharp.Core they should bind against). I then can't see how to make this binary work on machines that may have only one of FSharp.Core 4.3.0.0, 4.3.1.0 or 4.4.0.0. As it is essentially just a single-file application, should I convert it to C#?

**Comment by dsyme** [comment]
I see...  Could you put it in a sub-directory and resolve the FCS assembly reference to the shared component via an AssemblyLoad event resolver?

**Comment by dsyme** [comment]
Mind you it's a bit ugly to have FCS need a subdirectory.  Ugh.

**Comment by dsyme** [comment]
You could statically link FSharp.Core I guess.  It seems really unfortunate to rewrite it in C#, I'd prefer not to have C# in such a very base level F# tooling component. 

BTW could you call it FSharp.Compiler.Service.ProjectCracker.exe?

**Comment by dsyme** [comment]
BTW it's beginning to feel like the project cracking functionality should go in a new different nuget package,  FSharp.Compiler.Service.ProjectCracker, with a DLL and the .EXE tool (FSharp.Compiler.Service.ProjectCracker.Tool.exe or something) .  Then projects that need the functionality can opt-in to it and won't be surprised to see these extra files.

**Comment by rneatherway** [comment]
At the moment it is called `FSharp.Compiler.Service.ProjectCracker.exe`, I just called it `ProjectCracker.exe` for short. Currently the dependency is that `FCS.dll` references `FCSPC.exe`, but that could be reversed, or a tiny shared assembly could provide the common types for the two to talk to each other.

> I see... Could you put it in a sub-directory and resolve the FCS assembly reference to the shared component via an AssemblyLoad event resolver?

Yes, I thought about this, but I wasn't sure exactly how it would work. I suppose the resolver could scan Assembly.Load from a file on disk. I also thought it would be really ugly though.

> You could statically link FSharp.Core I guess.

Right, I guess I could depend on the FSharp.Core NuGet package and get it that way, then statically link. Worth a shot.

> BTW it's beginning to feel like the project cracking functionality should go in a new different nuget package, FSharp.Compiler.Service.ProjectCracker, with a DLL and the .EXE tool (FSharp.Compiler.Service.ProjectCracker.Tool.exe or something) .

What DLLs exactly are you thinking should go in here? Should it be completely separate from FCS? The two need to talk to each other somehow to get the correct types (I want it to return `FSharpProjectOptions`).

**Comment by dsyme** [comment]
@rneatherway I'm thinking that the API functionality to crack project options be removed from FSharp.Compiler.Service.dll and moved into a new DLL (in a new package), which depends on FCS.dll, and that new package also contain ProjectCracker.exe.  FCS.dll would not depend on either of these. This would be an API change but we'd mark the FCS APIs as deprecated.  

The new package would still be in this repo and part of the default build & test.

**Comment by dsyme** [comment]
In that scenario I mind less if ProjectCracker.exe is implemented in C# (since it leaves the primary FCS.dll entirely in F# with a low dependency base)

**Comment by rneatherway** [comment]
I appreciate the goal of a clean separation between FCS and the project cracking, but I'm not sure this idea actually achieves that. If we leave the old API in place, albeit deprecated, then the FCS dependency on MSBuild v12 remains, which causes these installation problems in some of the referenced issues. My current approach is the only way that prevents API breakage *and* removes the dependency on MSBuild v12 for FCS.dll.

I'd like to propose the following:

* Use JSON serialization to break the binary dependency between the two projects. Presumably this means using something built into .NET as we don't want FCS depending on other NuGet packages.
* Static-link FSharp.Core into FCSPR.exe, or FCSPR.exe to C# (No C# code would end up in FCS.dll). Then FCSPR.exe can remain in the same folder as FCS.dll.
* Leave FCSPR.exe in the same NuGet package. This is necessary to prevent API breakage.

What do you think?

**Comment by 7sharp9** [comment]
We've never had any problems calling the project cracking as an executable, no FSharp.Core issues.

**Comment by rneatherway** [comment]
Which FSharp.Core do you bundle with the addin?

**Comment by 7sharp9** [comment]
Hmmm the latest I think, so 4.4.0.0

**Comment by rneatherway** [comment]
Right, I think that's part of the issue. FCS isn't allowed to bundle FSharp.Core, hence the difficulty just being able to accept any version that might be lying around.

**Pull request closed without merging**
