### PR TITLE
integrate visualfsharp and fsharp master

### PR DESCRIPTION
**Pull request by dsyme**
The last ever nasty big integration (finally round-tripping the previous alignments)

### CODE REVIEW

**Comment by matthid** [comment]
@dsyme slack says this apparently blocks https://github.com/Microsoft/visualfsharp/issues/3469.
Any idea why the build went red or what is left to do here?

**Comment by Krzysztof-Cieslak** [comment]
I'm more concerned that it's blocker for https://github.com/fsharp/FsAutoComplete/issues/183 and support of `netstandard2.0` in Ionide. (`netcoreapp2.0` works file

**Comment by matthid** [comment]
@Krzysztof-Cieslak Yes that is basically what I meant, sorry.
I think the issues are basically duplicates (including https://github.com/fsharp/FsAutoComplete/issues/180) and all are on the wrong repository ;)

**Comment by dsyme** [comment]
It's close to being done. The problem is that the various software enginering procedures no longer quite align - e.g. this repo uses packages/... without version numbers, while Microsoft/visualfsharp  uses pnes with verison numbers.  I ws trying to wade my way through it but realised that I'd be better off aligning more things

 I'll try to get to it tomorrow

**Comment by matthid** [comment]
@dsyme thanks. If there is anything reasonable to help you with let me know. I'm basically blocked by this as well (I'm not even trying to update FAKE5 to SDK2 when I see such issues open).

**Comment by dsyme** [comment]
> I'm not even trying to update FAKE5 to SDK2 when I see such issues open

If I understand this blocks .NET Standard 2.0 consumption in Ionide.  Will definitely make this top priority.  I'm not sure I'll get time before Monday though

**Comment by cartermp** [comment]
> If I understand this blocks .NET Standard 2.0 consumption in Ionide

Yep, that is accurate.

**Comment by dsyme** [comment]
I'm closing this request and am going to do this another way.  I will make it possible to do builds of FCS in the visualfsharp repo, but I will also make sure it is possible to build just FCS in this repo.   But this repo will be a more-or-less direct subset of Microsoft/visualfsharp. just the parts needed for FCS, its documentation etc.

https://github.com/Microsoft/visualfsharp/pull/3480

**Pull request closed without merging**
