### PR TITLE
Use netcoresdk preview1

### PR DESCRIPTION
**Pull request by enricosada**
the .NET Core SDK is the preview1 ( latest released from http://dot.net ), was already like that but not is explicit.

fix to use only packages released on nuget.org, no dev packages from dev feeds

fix deps, NETCore.App is for console app, NETStandard.Library is of libraries (NETCore.App depends on NETStandard.Library, so i just removed useless dependencies, be lean)

btw about versions:

- rc2 is ok for .net core (corefx,bcl,coreclr)
- rc3 is oftern (always?) wrong, a dev package. there is not going to be a rc3, directly rtm after rc2
- preview1 is for tools/sdk packages

### CODE REVIEW

**Comment by ncave** [comment]
Just for the record, yes, MSBuild 0.1.0-preview-00022 is the latest rc2, but if you actually try to use it, it fails with a missing dependency on ms.tpl.dataflow. MSBuild 0.1.0-preview-00024-* looks better (yes, it's rc3, but at least no missing dependencies), but is not able to build older .fsproj projects either (see [#582](https://github.com/fsharp/FSharp.Compiler.Service/issues/582).

**Comment by dsyme** [comment]
Is there an MSBuild issues with repro entered about this?  Which fsproj files have the problem?

Thanks
Don

**Comment by enricosada** [comment]
@ncave We need to ask msbuild repo team, i's open now, can you open an issue there about older fsproj?

I'll open one about build and package. We need a package usable by preview1 (or preview2, but is the the same rc2 netcore) 
Problem is, it's not a good idea to use dev feed. 
Lot of strange stuff there ( rc2 rc3 ), and doing `-*` for deps may give wrong version or not working with preview1 sdk. 
Really it'is a pain to stay bleeding edge in dev feed, let's avoid it if possible, lost too much time. But now there is a working released preview1 so i am happy to use it and avoid pain

**Comment by ncave** [comment]
I have added an issue on the MSBuild repo: [#709](https://github.com/Microsoft/msbuild/issues/709)

**Pull request merged**
