### PR TITLE
Update FAKE to 4.1 and all build dependencies

### PR DESCRIPTION
**Pull request by forki**
This one uses the latest FCS to allow F# 4.0 in build scripts. Also dogfood

### CODE REVIEW

**Comment by dungpa** [comment]
While you're at it, could you help renovate the Release target?

Right now, NuGet push is not automatic; git tags and release notes may be out of sync with actual releases.

**Comment by forki** [comment]
Yep will do

**Comment by dsyme** [comment]
@forki - do you want to do that in a separate commit or as part of this one?

**Comment by forki** [comment]
I think I do a second one

**Pull request merged**
