### PR TITLE
Fsharp integration january 2020

### PR DESCRIPTION
**Pull request by baronfel**
Contains commits from 32b124966 to 5a0117048 from dotnet/fsharp.

Notable features:

* lowered allocations for large strings and char arrays (notable source file texts)
* improved support for byreflike rules with regards to type abbreviations
* better support for scopes in recursive modules
* better location of .net core reference assemblies
* lowered allocations for several internal compiler structures
* better error messages for anonymous record mismatches
* FSharpChecker learned how to keep background symbol uses
* Project cracker/project cracker tool were removed
* Better support for consuming C# inref parameters
* preview-level functionality for #r "nuget" in scripts

### CODE REVIEW

**Comment by baronfel** [comment]
A few new performance MRs were opened on dotnet/fsharp, I want to wait to get those in.

**Comment by goswinr** [comment]
does this update enable `#r: "nuget: PackageName"` in FCS ?

**Comment by baronfel** [comment]
@goswinr the code is there, yes, but as you say you'll need to enable preview. In addition there's not a released version of FSI to go with it, so any scripts you write would only be usable with tools that actually embed FCS for script execution instead of shelling out to FSI.

**Comment by goswinr** [comment]
thanks @baronfel 
so for ` #r: "nuget: ... "` in `FSI` I need to do just this?
```F#
let allArgs = [|"" ; "--langversion:preview" ; "--noninteractive" ; "--debug:full" ;"--optimize-" |]
let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration() 
let fsiSession = FsiEvaluationSession.Create(fsiConfig, allArgs, inStream, textwriter, textwriter)
fsiSession.EvalInteraction(codeString)
``` 

and for finding errors this:
```F#
let checker =  FSharpChecker.Create()
let sourceText = Text.SourceText.ofString (codeString)
let! options, optionsErr = checker.GetProjectOptionsFromScript(fileFsx,sourceText,otherFlags = [|"--langversion:preview" |]  )
let! parseRes , checkAnswer = checker.ParseAndCheckFileInProject(fileNameAndPath, 0, sourceText, options) 
```

**Comment by baronfel** [comment]
It _should_ be something similar to that, yes.  However, some notes on references and targeting:

* If you plan on targeting .net core, for typechecking at least you need to add the following in the call to `GetProjectOptionsFromScript`
  * `useSdkRefs = true`
  * `assumeDotnetFramework = false`
  * the value `"--targetprofile:netcore"` to the `otherFlags` array
* Then, you need to check the set of .net core referenced assemblies that are in the `options`. These will be of the form `-f:<path to reference>`.  In FSAC, we had to completely replace the set of assemblies that FSC provides as part of the 'default' F# script file options, because those were dependent on specific versions of .net core, and FSAC wanted to be able to typecheck for versions of .net core other than the one it was built using.  For example, FSAC runs as a `.netcoreapp2.2` process right now, but it needs to be able to typecheck `.netcoreapp3.1` programs.  You may want to look at the [reference-finding code](https://github.com/fsharp/FsAutoComplete/blob/master/src/ProjectSystem/FSIRefs.fs) or the differences we have between [.Net Framework and .Net Core script options](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L574-L588) for more detail

**Comment by baronfel** [comment]
It would also theoretically be possible for FAKE to start to make use of the new syntax after this release @matthid.

**Comment by baronfel** [comment]
Right now I'm choosing to wait for a couple dotnet/fsharp issues due to relevancy/performance:

* dotnet/fsharp#8252 (correctness fixes to package management)

**Comment by matthid** [comment]
Interesting I'm waiting a long time for a build to check if everything breaks apart. Let me know when it's ready (ping me again)

**Pull request merged**
