### PR TITLE
Integrate dotnet/fsharp from 4f5f08320 to 7b25d7f82

### PR DESCRIPTION
**Pull request by baronfel**
Notable changes include:

* Addition of the FsharpUnionCase.HasFields property
* FCS builds entirely on .Net Core now
* Better debug information for ranges
* Support for Literal values in signature files
* Using memory-mapped files cross-platform to read IL.

### CODE REVIEW

**Comment by nightroman** [comment]
@baronfel

Not sure if it is related to this update or my recent VS 16.4 update but on getting packages I see a new warning.

My `paket.dependencies`:

```
framework: net461
copy_local: false
references: strict

source https://www.nuget.org/api/v2
nuget FSharp.Compiler.Service
nuget FSharp.Core
nuget System.Collections.Immutable 1.5
nuget System.Reflection.Metadata 1.6
```
run (you can try in a separate directory with the above `paket.dependencies`)

    paket install

as a result it shows:

    Could not detect any platforms from 'netcoreapp3.1' in package System.Reflection.Metadata , please tell the package authors

After that my project builds fine and works as usual.
But the warning is new, I think you might need to know.

**Comment by baronfel** [comment]
What version of paket are you using at the moment?

**Comment by nightroman** [comment]
@baronfel 
Yes, my bad, I forgot that paket was involved as well...
With just updated Paket version 5.241.1 the warning is no more. Sorry for the false alarm.

**Comment by baronfel** [comment]
No problem, thank you for being proactive!

**Pull request merged**
