### PR TITLE
WIP: Write PDBs to stream instead of file

### PR DESCRIPTION
**Pull request by Alxandr**
This enables writing the PDB to a memory-stream when shimming the
file-system. Code mostly converted from Roslyn
(http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/InternalUtilities/ComStreamWrapper.cs,5dbd4388f94fa102)

### CODE REVIEW

**Comment by ctaggart** [comment]
The Portable PDB format looks like a great initiative to help with the pdb pain. I added links in https://github.com/ctaggart/SourceLink/issues/93.

**Comment by Alxandr** [comment]
I agree, though, this should probably be a separate issue.

On Fri, Jul 24, 2015 at 1:48 AM Cameron Taggart <notifications@github.com>
wrote:

> The Portable PDB format looks like a great initiative to help with the pdb
> pain. I added links in ctaggart/SourceLink#93
> <https://github.com/ctaggart/SourceLink/issues/93>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsharp/FSharp.Compiler.Service/pull/271#issuecomment-124271206>
> .
>
-- 
-- 
Alxandr

**Comment by ctaggart** [comment]
After talking to Roslyn team members at the MVP Summit, I think this should be solved by switching over completely to the portable pdb format and create #718 to track that.

**Comment by Alxandr** [comment]
@ctaggart as long as ppdbs can be consumed I completely agree. Also, since this PR is blocked by me not knowing COM, might probably just close it.

**Comment by dsyme** [comment]
Closing as this is now really old, we can resurrect if needed

**Comment by ashmind** [comment]
@dsyme @ctaggart
Question: is there currently a way to write pdbs (of any kind) into a virtual FS in F#?
A bit confused between this one and Microsoft/visualfsharp#718.

**Pull request closed without merging**
