### PR TITLE
Update build to latest and greates

### PR DESCRIPTION
**Pull request by forki**
as requested via https://github.com/fsharp/FSharp.Compiler.Service/pull/393#issuecomment-129428997

- [x] - Restore packages via paket
- [x] - tag git repo
- [x] - Create Github release via octokit
- [x] - Make AppVeyor run NuGet but not release target

### CODE REVIEW

**Comment by forki** [comment]
@dungpa what do you mean with "NuGet push is not automatic"? 

https://github.com/fsharp/FSharp.Compiler.Service/blob/master/build.fsx#L152 shows that a publisher only needs to provide it's key. this is like the recommended projectscaffold way (see http://fsprojects.github.io/ProjectScaffold/release-process.html#Setup-release-script)

**Comment by forki** [comment]
what else do you need?

**Comment by dungpa** [comment]
@forki I often use `Publish = true`. I don't if it makes any difference.

Could we make `Release` depend on `ReleaseDocs`? At the moment, `ReleaseDocs` is often out of sync.

Could we use prompt users and passwords as per https://github.com/fsprojects/ProjectScaffold/pull/200?

**Comment by dungpa** [comment]
@rneatherway Is there any problem with doing release using Octokit on Mono? I recalled you have to keep a private copy of Octokit for your projects.

**Comment by rneatherway** [comment]
@dungpa the version of Octokit in FAKE master has an `isMono` switch to avoid the connection retry logic that crashes on Mono 4.0.2. So everything should be fine. The crash is fixed in Mono master so after the next release we should be able to reinstate the retry logic.

**Pull request merged**
