### PR TITLE
F sharp merge 10 2015

### PR DESCRIPTION
**Pull request by brodyberg**
My first shot at this. 

Rough command-list used: 

git clone https://github.com/brodyberg/FSharp.Compiler.Service.git
git remote add fsharp https://github.com/fsharp/fsharp.git
git fetch fsharp
git checkout -b FSharpMerge_10_2015
git pull fsharp master

cd src/fsharp
git rm -r src/fsharp/FSharp.Build
git rm -r FSharp.Build-proto/ FSharp.Compiler FSharp.Core.Unittests/ FSharp.Core FSharp.Data.TypeProviders
git rm targets.make
git rm policy.2.0.FSharp.Core/Makefile.in
git rm policy.2.3.FSharp.Core/Makefile.in
git rm policy.3.259.FSharp.Core/Makefile.in
git rm policy.3.3.FSharp.Core/Makefile.in
git rm policy.3.47.FSharp.Core/Makefile.in
git rm policy.3.7.FSharp.Core/Makefile.in
git rm policy.3.78.FSharp.Core/Makefile.in
git rm policy.4.0.FSharp.Core/Makefile.in
git rm policy.4.3.FSharp.Core/Makefile.in

cd tests
git reset fsharp
git reset fsharpqa
 <<<<<<< Head

### CODE REVIEW

**Comment by dsyme** [comment]
Looks like something went wrong with this one :) will close

**Comment by dsyme** [comment]
Not sure what these were for?

    git reset fsharp
    git reset fsharpqa

**Comment by brodyberg** [comment]
I am looking for a better way to understand the full context in order to make the correct merge decisions. There must be more data than simply head, local and remote. 

As for the git reset fsharp etc, I think that was so that none of the changes in fsharp for those particular tests made it into fscs - because from what I could tell fscs did not have those directories.

**Comment by dsyme** [comment]
Hmmm... somehow how you ended up with a replay of the entire history of FSharp.Compiler.Service commits in this PR - I'm wondering if it was the "git reset" that caused that but reading the docs I don't think so. 

Re context on merge decsions - I don't know of anything better than looking back into the commit history.  "Blame" on github probably helps a lot.   Integrating commits one at a time may also help.

**Pull request closed without merging**
