### PR TITLE
ProjectCracker returns *.fsi files in FSharpProjectOptions.SourceFiles array

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
...and ProjectCracker throws exception if the Tool returns non null Error.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dsyme @enricosada @tpetricek Is it possible to see the Travis logs not being a this repo owner? I see this:

image

**Comment by abelbraaksma** [comment]
I think the problem isn't with the slashes. But somehow, nuget seems to try to access the wrong path. 

/cc @dsyme, it looks like you broke the build about a month ago with a merge and the Mac build hasn't completed successfully since:

image

**Comment by dsyme** [comment]
Thanks this is great.  Sorry it didn't make it into the last FCS release. We have to fix the travis build

**Comment by dsyme** [comment]
Working on it, see #816

**Comment by dsyme** [comment]
FCS 16.0.2 release

**Pull request merged**
