### PR TITLE
Integrate from fsharp\fsharp master

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
@ncave @enricosada This integration busts the .NET Core support.  I'm trying to work through the issues (first time I've looked closely at FCS support for .NET Core)

**Comment by ncave** [comment]
@dsyme I don't see any errors when I run `build RunTests.NetCore` on your branch.

**Comment by 7sharp9** [comment]
Last time I had mono and dnc installed at once it didn't compile.

**Comment by ncave** [comment]
The most recent FCS builds seem to have some issue with mono:latest (FSharp.Core reference missing, from briefly inspecting the Travis logs).

**Comment by dsyme** [comment]
@ncave I pushed a fix - there was some internal caching behaving incorrectly. One test fails - something to do with multiple StringBuilder types

The way we have to scrape the sample project in tests\...\Common.fs for a list of default reference assemblies for scripts (and just to get off the ground for projects) is awkward.  I suppose we'll have to bake that list into the compiler DLL or synthesize it via another technique

**Comment by dsyme** [comment]
> The most recent FCS builds seem to have some issue with mono:latest (FSharp.Core reference missing, from briefly inspecting the Travis logs), but it may or may not be a different issue.

Yes.  This is a different issue though.  We need to fix it...

**Comment by dsyme** [comment]
@ncave I fixed the problem with that .NET Core test I had to disable, and also enabled a few more .NET Core tests, see https://github.com/fsharp/FSharp.Compiler.Service/pull/641/commits/e9040628ac55bf14c8921b1659da563c9af1a713

**Pull request merged**
