### PR TITLE
bump version and prepare release notes for 27.0.1

### PR DESCRIPTION
**Pull request by baronfel**

### CODE REVIEW

**Comment by baronfel** [comment]
@dsyme or @enricosada can one of you please merge so I can stamp and publish a release?

**Comment by baronfel** [comment]
Hold off on this a moment, I'm going to remove the System.Data.SqlClient dependency from the project files and get that all hashed out before this release.

**Comment by baronfel** [comment]
Went ahead and integrated the 4 new commits dealing with System.Data.SqlClient and some rebuilds, to make sure the new version had a slimmer output nuget package.  Once this is merged I'll publish a new set of packages.

**Comment by dsyme** [comment]
Perfect!

**Comment by baronfel** [comment]
@dsyme mind merging this? I don't have the rights to.

**Comment by dsyme** [comment]
@baronfel You now have access, thanks

**Comment by baronfel** [comment]
Thanks, y'all. I'll try not to mess it up _too_ badly.

**Pull request merged**
