### PR TITLE
add Interactive Settings assembly to nuget package

### LINKED ISSUE #552: Nuget for FSharp.Compiler.Interactive.Settings.dll?
Would it be ok to create a Nuget package for this assembly?

It would make things a lot simpler for me if I can directly reference the dll from a known location on all platforms. This would be to workaround the [useFsiAux bug](https://github.com/fsharp/FSharp.Compiler.Service/issues/127#issuecomment-208392104)

### PR DESCRIPTION
**Pull request by nosami**
fixes #552

### CODE REVIEW

**Comment by 7sharp9** [comment]
We really need this, having the file missing makes this really broken in the current code as theres no way to use the API without the missing file.

**Comment by dsyme** [comment]
OK.  But we will almost certainly move it out into a separate nuget package at some point, once the bug that requires the presence of this DLL at all actually gets fixed.

**Comment by dsyme** [comment]
Actually, I think we can't do this.  We can't have every user of FSharp.Compiler.Service suddenly shipping their own FSharp.Compiler.Interactive.Settings.dll.  Let me take a look at the issue that's causing this to be required.

**Comment by nosami** [comment]
In that case, should I just make it a separate package now then?

**Comment by dsyme** [comment]
@nosami Yes, I suppose so.  I suppose really we should make it in http://github.com/fsharp/fsharp, since it's really one of the components of the F# programming model.  

FCS is _intended_ to not require any specific implementation of the ``fsi`` object. but rather to work with whatever is given as long as it has the right API. But for some reason a reference is still being required even when you pass in ``useFsiAux=false``

**Comment by nosami** [comment]
In my case, I need it to behave as much like fsharpi as possible

**Comment by dsyme** [comment]
@nosami OK, so you want to reference FSharp.Compiler.Interactive.Settings.dll, that's fair enough

Yes, please add a nuget package to http://github.com/fsharp/fsharp.  Push the first edition(s) of the package manually, no need to wait for the PR.  Put ``fsgit`` as an owner of the package in addition to yourself.

**Comment by dsyme** [comment]
@nosami Do you still need this?  I think we should close this otherwise

**Comment by nosami** [comment]
Just saw this, sorry. I forgot all about this. I worked around the issue
for now by adding the missing DLL to source control. I should fix this, but
the priority is low.

**Pull request closed without merging**
