### PR TITLE
Use Paket to create Nuget packages

### PR DESCRIPTION
**Pull request by forki**
implements https://github.com/fsharp/FSharp.Compiler.Service/issues/461

### CODE REVIEW

**Comment by nosami** [comment]
I get the following error when trying to run the new task on OSX

```
mono  /Users/jason/src/fsharp/FSharp.Compiler.Service/.paket/paket.exe pack output ./temp  version  1.4.2.1 releaseNotes  "#450 - Correct generation of ReferencedProjects"
Paket version 2.23.2.0
Unable to parse /Users/jason/src/fsharp/FSharp.Compiler.Service/tests/service/data/Malformed.fsproj:
      Data at the root level is invalid. Line 1, position 1.
Paket failed with:
	The file "../bin/v4.0/FSharp.Compiler.Service.xml" requested in /Users/jason/src/fsharp/FSharp.Compiler.Service/nuget/paket.template does not exist.
Running build failed.
Error:
System.Exception: Error during packing ..
  at Fake.Paket+Pack@78.Invoke (System.String message) <0x9cbac70 + 0x00027> in <filename unknown>:0
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () <0x3078f50 + 0x00030> in <filename unknown>:0
  at Microsoft.FSharp.Core.PrintfImpl+Final1@224[TState,TResidue,TResult,A].Invoke (Microsoft.FSharp.Core.FSharpFunc`2 env, A a) <0x3078d10 + 0x00085> in <filename unknown>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) <0x3078ce8 + 0x00024> in <filename unknown>:0
  at Fake.Paket.Pack (Microsoft.FSharp.Core.FSharpFunc`2 setParams) <0x9cb6000 + 0x0039a> in <filename unknown>:0
  at FSI_0001.Build+clo@137-16.Invoke (Microsoft.FSharp.Core.Unit _arg9) <0x891ff50 + 0x0001b> in <filename unknown>:0
  at Fake.TargetHelper+targetFromTemplate@155[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x9cabf38 + 0x00020> in <filename unknown>:0
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) <0x9ca36e8 + 0x000bd> in <filename unknown>:0
```

**Comment by forki** [comment]
Yes. One of the unittest data files is conflicting ;-)

I'm trying to work around that

**Comment by forki** [comment]
please retry with 4e58dc8

**Comment by nosami** [comment]
```
The file "../bin/v4.0/FSharp.Compiler.Service.xml" requested in /Users/jason/src/fsharp/FSharp.Compiler.Service/nuget/paket.template does not exist.
```

**Comment by forki** [comment]
and is it really not there?

**Comment by nosami** [comment]
ah.. it's FSharp.Compiler.Service.XML. Capital XML :)

**Comment by forki** [comment]
thx. will fix.
hope the travis build will find that too

**Comment by forki** [comment]
ah nuget target is disabled for travis. will enable first to see it fail

**Comment by forki** [comment]
Ok Travis found the issue in 7c9aaec.

**Comment by forki** [comment]
@nosami now it's complaining about the pdb. do you see the error?

**Comment by forki** [comment]
let me guess the mono build doesn't create pdbs

**Comment by nosami** [comment]
Got it! .mdb files are the equivalent

**Comment by forki** [comment]
bde41f1 should just add ?pb

**Comment by nosami** [comment]
Needs to be FSharp.Compiler.Service.dll.mdb

**Comment by forki** [comment]
I think it's ready to merge

**Comment by nosami** [comment]
Works for me

```
✔ ~/src/fsharp/FSharp.Compiler.Service/bin [paketpack ↓·1|✔]
12:19 $ l
total 18880
drwxr-xr-x   5 jason  staff      170 10 Nov 21:22 .
drwxr-xr-x  30 jason  staff     1020 10 Nov 21:22 ..
-rw-r--r--   1 jason  staff  9664085 10 Nov 21:22 FSharp.Compiler.Service.1.4.2.1.nupkg
drwxr-xr-x  27 jason  staff      918 10 Nov 21:18 v4.0
drwxr-xr-x  27 jason  staff      918 10 Nov 21:19 v4.5
```

**Comment by forki** [comment]
did you take a look into the nupkg?

2015-11-11 13:20 GMT+01:00 Jason Imison <notifications@github.com>:

**Comment by nosami** [comment]
```
12:28 $ tree
.
├── FSharp.Compiler.Service.nuspec
├── [Content_Types].xml
├── _rels
├── lib
│   ├── net40
│   │   ├── FSharp.Compiler.Service.XML
│   │   ├── FSharp.Compiler.Service.dll
│   │   └── FSharp.Compiler.Service.dll.mdb
│   └── net45
│       ├── FSharp.Compiler.Service.XML
│       ├── FSharp.Compiler.Service.dll
│       └── FSharp.Compiler.Service.dll.mdb
└── package
    └── services
        └── metadata
            └── core-properties
                └── coreProp.psmdcp

8 directories, 9 files
```

**Comment by forki** [comment]
yeah and the nuspec looked also good

**Comment by nosami** [comment]
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>FSharp.Compiler.Service</id>
    <version>1.4.2.1</version>
    <authors>Microsoft Corporation, Dave Thomas, Anh-Dung Phan, Tomas Petricek</authors>
    <licenseUrl>https://github.com/fsharp/FSharp.Compiler.Service/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/fsharp/FSharp.Compiler.Service</projectUrl>
    <iconUrl>https://raw.github.com/fsharp/FSharp.Compiler.Service/master/misc/logo.png</iconUrl>
    <description>The F# compiler services package contains a custom build of the F# compiler that
exposes additional functionality for implementing F# language bindings, additional
tools based on the compiler or refactoring tools. The package also includes F#
interactive service that can be used for embedding F# scripting into your applications.</description>
    <summary>F# compiler services for creating IDE tools, language extensions and for F# embedding.</summary>
    <releaseNotes>#450 - Correct generation of ReferencedProjects</releaseNotes>
    <tags>F# fsharp interactive compiler editor</tags>
  </metadata>
</package>
```

**Comment by dsyme** [comment]
Awesome work guys

**Comment by dsyme** [comment]
@forki We started getting unit test failures after this, see https://travis-ci.org/fsharp/FSharp.Compiler.Service/builds.  Is it because there is still a packages.config here?

   C:\GitHub\dsyme\FSharp.Compiler.Service\docs\tools\packages.config
   C:\GitHub\dsyme\FSharp.Compiler.Service\tests\service\data\sqlite-net-spike



```
Errors and Failures:
1) Test Failure : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- 2nd level references
     Expected: "Found 'Test1.dll'"
Actual: "Failed to find 'Test1.dll'"
  Expected string length 17 but was 26. Strings differ at index 1.
  Expected: "Found 'Test1.dll'"
  But was:  "Failed to find 'Test1.dll'"
  ------------^

at FsUnit.shouldEqual[a] (a x, a y) <0x41e11d10 + 0x00143> in <filename unknown>:0
at FSharp.Compiler.Service.Tests.ProjectOptionsTests.checkOption (System.String[] opts, System.String s) <0x426e8a40 + 0x00128> in <filename unknown>:0
at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- 2nd level references () <0x426e8670 + 0x00180> in <filename unknown>:0

2) Test Failure : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- multi language project
     Expected: "Found 'ConsoleApplication2.exe'"
Actual: "Failed to find 'ConsoleApplication2.exe'"
  Expected string length 31 but was 40. Strings differ at index 1.
  Expected: "Found 'ConsoleApplication2.exe'"
  But was:  "Failed to find 'ConsoleApplication2.exe'"
  ------------^

at FsUnit.shouldEqual[a] (a x, a y) <0x41e11d10 + 0x00143> in <filename unknown>:0
at FSharp.Compiler.Service.Tests.ProjectOptionsTests.checkOption (System.String[] opts, System.String s) <0x426e8a40 + 0x00128> in <filename unknown>:0
at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- multi language project () <0x426ee5c0 + 0x0016b> in <filename unknown>:0

3) Test Failure : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- reference project output file
     Expected: collection containing "/home/travis/build/fsharp/FSharp.Compiler.Service/tests/service/data/DifferingOutputDir/Dir1/OutputDir1/Test1.dll"
  But was:  < "/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll", "/usr/lib/mono/4.0/mscorlib.dll", "/usr/lib/mono/4.0/System.dll", "/usr/lib/mono/4.0/System.Core.dll" >

at FsUnit.should[a,a] (Microsoft.FSharp.Core.FSharpFunc`2 f, a x, System.Object y) <0x423e9430 + 0x001f9> in <filename unknown>:0
at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- reference project output file () <0x426f3480 + 0x00266> in <filename unknown>:0

```

**Comment by dsyme** [comment]
@forki forget that - the failures are caused by changing from Mono 4.0.5 to Mono 4.2.1

**Comment by forki** [comment]
Unfortunately we have lots of issues with latest mono. FAKE's own build is
flaky now.

**Comment by dsyme** [comment]
ok, thanks

**Pull request merged**
