### PR TITLE
Fix 177

### PR DESCRIPTION
**Pull request by dsyme**
Fixes https://github.com/fsharp/FSharp.Compiler.Service/issues/177

### CODE REVIEW

**Comment by rojepp** [comment]
Neat! Shouldn't this go into visualfsharp first?

**Comment by dsyme** [comment]
We are currently accepting symbol/autocomplete-related fixes into FCS. These can certainly be folded back into Microsoft\visualfsharp, but further testing would be needed.  Also some of the fixes don't deeply affect the Visual F# Tools since they primarily affect colorization information more than autocomplete.

**Comment by rojepp** [comment]
Alright, thanks.

**Comment by dungpa** [comment]
It's fixed, finally. I wholeheartedly thank you for this :-).

**Pull request merged**
