### PR TITLE
integrate visualfsharp master and bump version to 17.0.1

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
Failing on travis: 
```
[?1l>[39;49m[32m/home/travis/.local/share/dotnetcore/dotnet restore tools.fsproj
[37mï»¿ï»¿Failed to load ï¿½j', error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/travis/.local/share/dotnetcore/shared/Microsoft.NETCore.App/2.0.0/libcoreclr.so'
[31mRunning build failed.
Error:
System.Exception: dotnet restore tools.fsproj failed
  at Microsoft.FSharp.Core.PrintfModule+PrintFormatToStringThenFail@1379[TResult].Invoke (System.String message) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+Final1@224[TState,TResidue,TResult,A].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a) [0x00038] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at FSI_0005.Build.runDotnet (System.String workingDir, System.String args) [0x00043] in <8e63edb815f040ddbe164ca503ed2a75>:0 
  at FSI_0005.Build+clo@90-1.Invoke (Microsoft.FSharp.Core.Unit _arg2) [0x000ca] in <8e63edb815f040ddbe164ca503ed2a75>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <59b649fdccf1c534a7450383fd49b659>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <59b649fdccf1c534a7450383fd49b659>:0 
```

**Comment by dsyme** [comment]
@forki It looks like the wrong ``dotnet`` is being run by this?

   let dotnetExePath = DotNetCli.InstallDotNetSDK "2.0.2"

I don't yet understand why, unless it is a bug in FAKE's ``DotNetCli.InstallDotNetSDK``

**Comment by dsyme** [comment]
@forki @matthid If you could have a look at the failure on Travis related to the install of .NET SDK and restore of ``fcs\tools.proj`` I'd be really grateful

**Comment by enricosada** [comment]
@dsyme sent https://github.com/dsyme/FSharp.Compiler.Service/pull/1

if you can enable push to PR for maintaners, i can fix these kind of errors (forki too) directly to PR

**Comment by forki** [comment]
That is the weird failure that I had in that other pr. I have no idea.
2.0.2 is working fine for safe stack build on Travis

Am 03.11.2017 18:31 schrieb "Don Syme" <notifications@github.com>:

**Comment by enricosada** [comment]
@forki issue was .net core runtime dependencies, arent always installed by default

**Comment by dsyme** [comment]
@enricosada Thank you so much!

**Pull request merged**
