### PR TITLE
integrate visualfsharp's latest master

### PR DESCRIPTION
**Pull request by baronfel**
This seems to be ok, the tests and nuget seems to work alright, with one exception:

There are two tests that key off of the methods on `System.String`, but in some tests runs they include the new `AsMemory` and `AsSpan` methods, but some they do not.

### CODE REVIEW

**Comment by baronfel** [comment]
This should help solve #884

**Comment by dsyme** [comment]
Thank you!

**Comment by dsyme** [comment]
Could you do an fcs version bump as well? https://github.com/fsharp/FSharp.Compiler.Service/blob/master/fcs/fcs.props#L6

**Comment by dsyme** [comment]
Bump to 26.0.1 and search for 25.0.1 to check we get all occurrences

**Comment by dsyme** [comment]
@baronfel Can you do the version bump in another PR? thanks :)

**Comment by baronfel** [comment]
Yep, I'll get right on that. Thanks for the review/merge @dsyme!

**Pull request merged**
