### PR TITLE
make Internal.Utilities.Text.Lexing.Position a struct

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Heap allocation before:
position-is-record
After:
position-is-struct-2

### CODE REVIEW

**Comment by dsyme** [comment]
Hi @vasily-kirichenko 

This is potentially a good change. A couple of things

* Although allocations will reduce, it's possible that the lexer and parser become slower (because more time is spent copying structs). Could you write a perf test to repeatedly parse some input?  I don't think it matters too much which input it is.

* Ideally this change would via  Microsoft/visualfsharp --> fsharp/fsharp --> fsharp/FSharp.Compiler.Service to keep the codebases maximally aligned. Would you be able to submit the change to Microsoft/visualfsharp and assess its impact on perf of a compiler bootstrap?

Thanks
Don

**Comment by vasily-kirichenko** [comment]
Hi, Don.

How exactly I can run parsing on a file? If I use `FSharpChecker.ParseFileInProject`, it caches results and all subsequent calls returns immediately.

**Comment by dsyme** [comment]
I guess you could generate a sequence of textually different files?

**Comment by vasily-kirichenko** [comment]
I've tested it on all *.fs files in src/fsharp dir https://github.com/vasily-kirichenko/FSharp.Compiler.Service/blob/parser-perf/tests/ConsoleApplication1/Program.fs 

Results: before - 6.7 s, after - 7.03 s, which is roughly 5% digression :(   

Memory traffic (all objects created during the parsing), before:

before_memory

after:

after_memory

Now `Tuple<Position, Position>` takes almost 2x more memory. Maybe it's a good idea to replace it with a custom struct?

**Comment by vasily-kirichenko** [comment]
I replaced a couple of top allocated `Tuple`s with custom structs and make a couple of functions to be top-level. After that parsing time reduced and equals 6.26 s (6% better than "before" result). Number of allocated objects reduced by 45% (!), allocated memory - by 9%. I tried to make `TokenTup` to be a struct, but it increased parsing time by 10%. 

after_2_memory

**Comment by dungpa** [comment]
@dsyme Have you had a second look at this PR? It seems like a good enhancement to make.

**Comment by dsyme** [comment]
> I replaced a couple of top allocated  Tuple s with custom structs and make a couple of functions to be top-level. After that parsing time reduced and equals 6.26 s (6% better than "before" result). Number of allocated objects reduced by 45% (!), allocated memory - by 9%. 

@vasily-kirichenko Is this what's currently in the PR?  Thx.

**Comment by dsyme** [comment]
(I'll reopen since there does seem to be value here, once we confirm the tradeoffs)

**Comment by vasily-kirichenko** [comment]
@dsyme yes.

**Comment by dsyme** [comment]
@vasily-kirichenko Would it be possible for you to submit this to Microsoft\visualfsharp as well please?  I don't mind accepting it here first but ideally we should get it submitted there too.

**Comment by vasily-kirichenko** [comment]
@dsyme done https://github.com/Microsoft/visualfsharp/pull/664

**Pull request merged**
