### PR TITLE
Fix caching, rewrite FCS reactor queue

### PR DESCRIPTION
**Pull request by dsyme**
Title says it. The caches were being missed in many cases, and the lookup of the caches was often asynchronously disconnected from the code to update that cache.

Also add tracing to get intelligible info about the request queue via Debug.WriteLine.  This goes to the output window of Visual Studio. For example when tracing the request queue for VFPT you can start an instance of devenv.exe under another VS debugger:

     devenv /debugexe devenv.exe

However this currently requires using a debug build of FSharp.Compiler.Service

### CODE REVIEW

**Comment by 7sharp9** [comment]
Would this potentially help with the dirty notify issues Ive mentioned before?  I have no idea of the context which might of changed when I do get the notifications they are just normal parse requests.

**Comment by dsyme** [comment]
I know you sent some details by email, but could you enter that as an issue in this repo, with repro steps or a failing test?

**Comment by vasily-kirichenko** [comment]
I tried this build on VFPT solution and VS's memory reached 2.3GB in 20 minutes :(

**Comment by dsyme** [comment]
@vasily-kirichenko I wasn't expecting this one to fix any specific memory problems.

**Pull request merged**
