### PR TITLE
[Test only] Apply changes from VF# Jenkins build activation

### PR DESCRIPTION
**Pull request by forki**
details at https://github.com/Microsoft/visualfsharp/pull/3788

### CODE REVIEW

**Comment by dsyme** [comment]
@forki These should be applied by a integration/merge from Microsoft/visualfsharp master --> fsharp/FSharp.Compiler.Service master, rather than a separate commit

I'll close - can you do the integration PR instead?  You may need to ``git rm`` and ``git add`` on changed files that are in visualfsharp but not in FCS, e.g.

    git rm -fr vsintegration
    git rm -fr setup
    git rm -fr src\fsharp\FSharp.Compiler

and a bunch of other stuff - the conflict list should only contain such stuff

After integration the two repos should be more or less equal content-wise

**Comment by forki** [comment]
Sorry I wasn't clear here. This wasn't meant to be merged. I wanted to cross check if my changes in VF# still work here. And for unknown reasons Travis failed during restore. Can you please reopen?

**Comment by dsyme** [comment]
@forki OK, thanks

**Comment by dsyme** [comment]
Closing as will be covered by integration

**Pull request closed without merging**
