### PR TITLE
Fix ProjectFileNames order when getting project options from script 

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This is more of an issue/question than a PR but I wanted to include the code to better illustrate my point.

I would like to make it possible just to use F# scripts instead of a `fsproj` file. However, compilation of scripts quickly fails when the file structure complicates a bit. Consider we have the following four files:

- `BaseLib.fs`
- `Lib1.fsx` (loads `BaseLib.fs`)
- `Lib2.fsx` (loads `BaseLib.fs`)
- `Main.fsx` (loads `Lib1.fsx`, `Lib2.fsx`)

When I call `FSharpChecker.GetProjectOptionsFromScript` on `Main.fsx` I get the following file ordering, which makes compilation fail:

```
Lib1.fsx
BaseLib.fs
Lib2.fsx
Main.fsx
```

Of course this is fixed if I load `BaseLib.fs` before anything in `Main.fsx` but, given that `GetProjectOptionsFromScript` actually finds `BaseLib.fs`, I wonder if it would be possible to fix the ordering so `Main.fsx` doesn't need to know `Lib1.fsx` dependencies in advance.

The fix in this PR does actually this, however I got it by trial-and-error and I didn't test with other file structures so probably there's a much better solution. My question, would something along these lines be possible (so it's worth working on it) or is there any reason it's bound to fail in certain situations?

Thanks!

### CODE REVIEW

**Comment by cloudRoutine** [comment]
Shouldn't this be addressed inside FSharp.Compiler.Service?

**Comment by 7sharp9** [comment]
I thought this already happened?  How would scripts ever have worked?

**Comment by alfonsogarciacaro** [comment]
Seems I didn't make a good job to explain the problem 😉  I'll try to fix that:

- Duplicates are not a problem and are indeed removed, that's why `BaseLib.fs` is not loaded twice even if it's loaded by both `Lib1.fsx` and `Lib2.fsx`.
- From my understanding (I might be wrong), this is how FCS is reading the source files at the moment when getting the project options from the script:

1. FCS reads the first `#load` directive of `Main.fsx` so it adds `Lib1.fsx` to the list of source files.
2. FCS then reads the `#load` directives of `Lib1.fsx` (in this case `BaseLib.fs`) and puts them **after** the previously loaded files.
3. FCS reads the next `#load` in `Main.fsx`, which is `Lib2.fsx` and repeats step 2. But as `BaseLib.fs` has already been added it doesn't add anything to source files besides `Lib2.fsx`.

In super-simplified and imperative (because that is what we love :wink:) code this would become:

```fsharp
    type LoadDirective = { file: File }
    and File = { path: string; loadDirectives: LoadDirective list }

    let rec getProjectSourceFiles (sourceFiles: ResizeArray<string>) (file: File) =
        for loadDirective in file.loadDirectives do
            sourceFiles.Add(loadDirective.file.path)
            getProjectSourceFiles sourceFiles loadDirective.file

    let sourceFiles = ResizeArray<string>()
    getProjectSourceFiles sourceFiles mainFile
```

So my naive thinking it's the problem can be solved by swapping the lines within the for loop in the above code (so the dependencies of a file are added to the sourceFiles list before the file itself). Is that correct?

I hope it's a bit clearer now and I didn't mess things further. If you want me to create a repo with the sample files I'm talking about, just tell me.

**Comment by matthid** [comment]
This is the fix for https://github.com/fsharp/FSharp.Compiler.Service/issues/587, correct?

**Comment by matthid** [comment]
It clearly looks like someone was doing "distinct" on the reverted list.

**Comment by alfonsogarciacaro** [comment]
Yeah, it seems to be related to #587, I didn't notice that. Thanks for pointing it out!

**Comment by dsyme** [comment]
@alfonsogarciacaro Do you know if this bug manifests in the Visual F# Tools (fsi.exe and its language service)?  Should we be making a corresponding fix there?

**Comment by 0x53A** [comment]
@dsyme 
Here (https://github.com/fsharp/FAKE/issues/1263) is a comparison between FSI and FSharp.Compiler.Service:

1.fsx

```F#

#load "2.fsx"
#load "3.fsx"

printfn "HELLO FROM 1"
```

2.fsx

```F#

#load "4.fsx"

printfn "HELLO FROM 2"
```

3.fsx

```F#

#load "4.fsx"

printfn "HELLO FROM 3"
```

4.fsx

```F#
printfn "HELLO FROM 4"
```


```

C:\Users\lr\Source\Repos\Test>"C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe" 1.fsx
HELLO FROM 4
HELLO FROM 2
HELLO FROM 4
HELLO FROM 3
HELLO FROM 1

C:\Users\lr\Source\Repos\Test>packages\fake\tools\fake.exe 1.fsx
HELLO FROM 2
HELLO FROM 4
HELLO FROM 3
HELLO FROM 1

```
(I run fake.exe, but it uses  FSharp.Compiler.Service internally)

FSI executes script 4 twice, while FSharp.Compiler.Service executes each script exactly once, but in the wrong order.

**Comment by alfonsogarciacaro** [comment]
I'm on OSX/Mono and I'm getting similar results, `fsharpi` loads files in the proper while `fsharpc` fails. I'll try to investigate what's the difference between both workflows.

MyLib.fs
```fsharp
let add2 x = x + 2
```

MyLib1.fsx
```fsharp
#load "MyLib.fs"
let add3 = MyLib.add2 >> ((+) 1)
```

MyLib2.fsx
```fsharp
#load "MyLib.fs"
let add4 = MyLib.add2 >> ((+) 2)
```

Main.fsx
```fsharp
#load "MyLib1.fsx"
#load "MyLib2.fsx"
MyLib1.add3 5 |> printfn "%i"
MyLib2.add4 5 |> printfn "%i"
```

```shell
$ fsharpi Main.fsx 
8
9

$ fsharpc Main.fsx
F# Compiler for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

/temp/MyLib1.fsx(4,6): error FS0039: The namespace or module 'MyLib' is not defined

/temp/MyLib1.fsx(7,12): error FS0039: The value or constructor 'add2' is not defined
```

**Comment by alfonsogarciacaro** [comment]
There are two similar options [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/CompileOps.fs#L5049-L5058).

The first one is called by `GetProjectOptionsFromScript`, which Fable uses and what I tested for this PR. According to the comment, the second one is called both by `fsi` and `fsc` but they deal with the result differently:

fsi
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L1217

fsc
https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsc.fs#L233

**Comment by alfonsogarciacaro** [comment]
As @matthid pointed out, the problem seems to be with grouping in [this line](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/CompileOps.fs#L5012): `List.groupByFirst`.

I undid changes in the previous commit and just used closure's `Inputs` instead of `SourceFiles` (the same way as [fsi does](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L1231-L1232)) to build the Project Options [here](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/vs/service.fs#L2552) and the fix still applies. At least for Fable which uses `GetProjectOptionsFromScript`, I guess this is not yet enough to fix `fsc`.

**Comment by alfonsogarciacaro** [comment]
I've changed the name of the PR. Please let me know if it can be accepted just as a patch for `GetProjectOptionsFromScript` or you want me to give it a shot at fixing `fsc` too. I'm not sure yet how to do that though. Maybe just removing `Lists.groupByFirst` from [this line](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/CompileOps.fs#L5012) as commented above?

**Comment by dsyme** [comment]
@alfonsogarciacaro Could you add a test case please? That would clarify the change for me. Thanks

**Comment by dsyme** [comment]
@alfonsogarciacaro  We've now integrated all the changes from visualfsharp.  Could you merge with master and update the PR please?  Thanks

**Comment by dsyme** [comment]
Closing and reopening to trigger CI

**Comment by alfonsogarciacaro** [comment]
Hi Don, I've rebased with latest master and added the test. Checking the test I realised that my second "fix" was actually wrong (replacing `SourceFiles` with `Inputs` is not enough) so I went back to the original solution.

In any case, I'd appreciate if you can have a look. This is working now for my use case but I haven't managed to run the other tests, so I don't know if I'm breaking something else. `build.fsx` refuses to work on my machine and Travis is hanging forever 😕

**Comment by alfonsogarciacaro** [comment]
@dsyme, with the latest commit, only the tests that are also failing on `master` are failing now. Again, it'd be best if someone with a better knowledge of the code could review it, as I did the changes mostly by trial-and-error. For example, I'm not sure if I need to do something else with [the other members of `LoadClosure`](https://github.com/alfonsogarciacaro/FSharp.Compiler.Service/blob/eee89ff5fd8bd40f15989d78a8579e10be44fa53/src/fsharp/CompileOps.fs#L5059-L5063).

**Comment by alfonsogarciacaro** [comment]
I realized my previous fix wasn't working in all situations so I've added more tests and improved it. What confused me was the `GetAvailableLoadedSources` function, which loaded more files than expected (I thought it was only loading dependencies of the current file). I've fixed that by setting a file as observed [right after confirming it hasn't been](https://github.com/fsharp/FSharp.Compiler.Service/pull/594/files#diff-5e8da4b6097c90ff578d4c96bfef51f1R4983). This seems to work and the new tests are passing but, as usual, I'm exploring uncharted territory so reviews are appreciated.

**Comment by alfonsogarciacaro** [comment]
@dsyme, I rebased the PR against the latest changes in master and now build checks are passing 🎉 Also, I published a Fable version with a custom build including this fix and there have not been errors reported so far. If the PR is merged, how should this fix be propagated to the F# compiler? Should I send another PR to the fsharp or visualfsharp repo? Cheers!

**Comment by dsyme** [comment]
I've confirmed that [the broken behaviour reported above](https://github.com/fsharp/FSharp.Compiler.Service/pull/594#issuecomment-228876293) also repros on F# 4.0 on Windows.

It also repros when ``fsi --load:Main.fsx`` is used.

So yes, we wiwll also need to propagate this fix to the visualfsharp repository.  I'll just cherry-pick it and send a PR there since it's quite important to fix

**Comment by dsyme** [comment]
Fix in visualfsharp is here: https://github.com/Microsoft/visualfsharp/pull/1363

**Comment by dsyme** [comment]
@alfonsogarciacaro We have failing tests in visualfsharp after this change, see https://github.com/Microsoft/visualfsharp/pull/1363

We'd better get those sorted out

**Comment by alfonsogarciacaro** [comment]
@dsyme, thanks for that! I'll try to move the tests to FCS and fix them here :+1:

**Comment by dsyme** [comment]
@alfonsogarciacaro I think the errors are all of this form below. This is for ``tests\fsharp\core\attributes``, running

    ..\..\..\..\Debug\net40\bin\FsiAnyCPU.exe  testlib.fs test.fsx

Note that ``testlib.fs`` occurs both on the command line and as a ``#load`` in test.fsx

```
C:\GitHub\dsyme\visualfsharp\tests\fsharp\core\attributes>..\..\..\..\Debug\net4
0\bin\FsiAnyCPU.exe -r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerr
ors:1 --abortonerror testlib.fsi testlib.fs test.fsx


warning FS0075: The command-line option '--abortonerror' is for test purposes on
ly


testlib.fsi(4,1): error FS0238: An implementation of file or module 'FSI_0001_Te
stLibModule' has already been given. Compilation order is significant in F# beca
use of type inference. You may need to adjust the order of your files to place t
he signature file before the implementation. In Visual Studio files are type-che
cked in the order they appear in the project file, which can be edited manually
or adjusted using the solution explorer.
```

**Comment by alfonsogarciacaro** [comment]
That's very valuable info! We may fix it by passing and initial value to the [observed sources](https://github.com/alfonsogarciacaro/FSharp.Compiler.Service/blob/d06a42482eb231a787eae97e25250550e326ece9/src/fsharp/CompileOps.fs#L4974) (the sources that were passed on the command line). I'll give it a try.

**Comment by dsyme** [comment]
@alfonsogarciacaro Updated the information above - the bug appears with

    #load "testlib.fsi" "testlib.fs" 

in the script

**Comment by dsyme** [comment]
@alfonsogarciacaro The bug in ``tests\fsharp\core\reflect`` is different

    ..\..\..\..\Debug\net40\bin\FsiAnyCPU.exe test.fs test2.fs

The order test2.fs and test.fs is reversed from the command line arguments:

```
[Loading C:\GitHub\dsyme\visualfsharp\tests\fsharp\core\reflect\test2.fs
 Loading C:\GitHub\dsyme\visualfsharp\tests\fsharp\core\reflect\test.fs]

test2.fs(25,6): error FS0039: The namespace or module 'Test' is not defined
```

**Comment by dsyme** [comment]
@alfonsogarciacaro Finally, the ``LoadingFsx.fsx`` and ``LoadingFsx.fsscript`` failures are because it seems in F# 4.0 a script can ``#load`` itself without failure, e.g. consider

    C:\GitHub\dsyme\visualfsharp\tests\fsharpqa\Source\InteractiveSession\Misc\LoadingFsx.fsx

which contains 

```
// #NoMT #FSI 
// It is ok to #load an .fsx file
//<Expects status="success"></Expects>

let x1 = 1

#if INTERACTIVE

#load "LoadingFsx.fsx"

#endif

let x2 = 2

#q;;
```

The test is running 

    ..\..\..\..\Debug\net40\bin\fsc.exe LoadingFsx.fsx

from 

    C:\GitHub\dsyme\visualfsharp\tests\fsharpqa\Source\InteractiveSession\Misc

**Comment by dsyme** [comment]
Removing the List.rev from this line looks promising:

```
        let protoClosure = files |> List.map (fun (filename,m)->SourceFileOfFilename(filename,m,tcConfig.inputCodePage)) |> List.concat |> List.rev // Reverse to put them in the order they will be extracted later
```

**Comment by dsyme** [comment]
@alfonsogarciacaro I pushed two fixes to the visualfsharp PR that should I think address these problems

https://github.com/Microsoft/visualfsharp/pull/1363/commits/b7bb99d774fb86209e7993a6bb0ff689799905b4

**Comment by dsyme** [comment]
Let's get it green there then cherry-pick the fix-on-fix back here

**Comment by dsyme** [comment]
I checked most of the failing tests by hand and they seem to now be ok.

**Comment by alfonsogarciacaro** [comment]
Wow, you're fast! Ok, if everything is green in visualfsharp I can do the cherry-picking and send a new PR here if you want. Thanks a lot for your help!

**Comment by alfonsogarciacaro** [comment]
Previous failing tests now pass but there's a new failure 😞 I'm not sure how serious it is.

```
1) Failed : FSharp-Tests-Core+Load-Script.load-script
'C:\projects\visualfsharp-3dtit\tests\fsharp\core\load-script\out.stdout.txt' and 'C:\projects\visualfsharp-3dtit\tests\fsharp\core\load-script\out.stdout.bsl' differ; ["diff between [C:\projects\visualfsharp-3dtit\tests\fsharp\core\load-script\out.stdout.txt] and [C:\projects\visualfsharp-3dtit\tests\fsharp\core\load-script\out.stdout.bsl]";
 "line 10"; " - -the end"; " + Hello"]
```

**Comment by alfonsogarciacaro** [comment]
@dsyme, I tried rebuilding FCS applying your latest fix and unfortunately `FSharpChecker.GetProjectOptionsFromScript` doesn't seem to return the file names of any `#load` directive.

**Comment by dsyme** [comment]
Yeah, I know.  I've made a better set of changes in https://github.com/Microsoft/visualfsharp/pull/1363, I think things are healthier now.

**Comment by dsyme** [comment]
Cherry picked here.  When both FCS and visualfsharp are green then we are in good shape https://github.com/fsharp/FSharp.Compiler.Service/pull/611

**Pull request merged**
