### PR TITLE
update version to 26.0.1

### PR DESCRIPTION
**Pull request by baronfel**
Added release notes, updated version prefix, and updated the README to 26.0.1.

### CODE REVIEW

**Comment by dsyme** [comment]
Super.  Do you have permissions to push the nuget?

**Comment by baronfel** [comment]
No I do not

**Comment by dsyme** [comment]
OK I'll get those to you

**Comment by dsyme** [comment]
baronfel on nuget?

**Comment by baronfel** [comment]
chethusk, confusingly enough.

**Comment by baronfel** [comment]
Thanks! I'll push 26.0.1 in a bit then.

**Comment by baronfel** [comment]
I was able to push the 26.0.1 version of `FSharp.Compiler.Service`, but I was unable to push corresponding versions of `FSharp.Compiler.Service.ProjectCracker` and `FSharp.Compiler.Service.MSBuild`

**Comment by dsyme** [comment]
I gave you permission to FSharp.Compiler.Service.ProjectCracker but not  FSharp.Compiler.Service.MSBuild.v12 yet - will be able to do the latter tomorrow

**Comment by alfonsogarciacaro** [comment]
I just downloaded FSharp.Compiler.Service 26.0.1 and when trying to parse a file containing just an anonymous record: `let x = {| X = 5 |}`, I get the following:

```
ENTITY: QuickTest
        VALUE: QuickTest.x
<ToString exception: unhandled construct in AST at /Users/alfonsogarciacaronunez/dev/fable_master/src/tools/QuickTest.fs (3,8--3,19) IsSynthetic=false>
```

Am I doing something wrong?

**Comment by baronfel** [comment]
Uploaded the ProjectCracker nuget, will upload the MSBuild one after permissions are cleared up 👍

**Pull request merged**
