### PR TITLE
Fix line endings in the Nuget packages descriptions

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by abelbraaksma** [comment]
Thanks, but how can this change possibly fail the build?

**Comment by vasily-kirichenko** [comment]
The Travis build failing on master as well. No idea why.

**Comment by abelbraaksma** [comment]
A quick look shows it fails on Linux and Mac. It seems to have trouble with locating `MicroBuild.Core.Sentinel`, but doesn't break / fail on that. Later it fails with NuGet.

image

It seems NuGet can't find a path:

image

**Comment by vasily-kirichenko** [comment]
@abelbraaksma I replaced the slashed to the linux ones in https://github.com/fsharp/FSharp.Compiler.Service/pull/812, waiting for results...

**Comment by vasily-kirichenko** [comment]
@abelbraaksma how did you manage to see the Travis build logs?

**Comment by abelbraaksma** [comment]
> @abelbraaksma how did you manage to see the Travis build logs?

@vasily-kirichenko,  by clicking on Details:

image

And in the next window, clicking on whatever line I though interesting, this gave me a screen with colored log lines:

image

**Comment by dsyme** [comment]
16.0.2 released

**Pull request merged**
