### PR TITLE
Add noframework option in AST compiler methods

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
I added this option to the AST compiler methods in order to work around [this issue](https://github.com/fsharp/FSharp.Compiler.Service/issues/258#issuecomment-62381514) in my [QuotationCompiler](https://github.com/eiriktsarpalis/QuotationCompiler/) library.

### CODE REVIEW

**Comment by 7sharp9** [comment]
So this removes an implicit FSharp.Core reference?

**Comment by eiriktsarpalis** [comment]
Yes, same as `--noframework` in `fsc.exe`.

**Comment by 7sharp9** [comment]
@dsyme Why is there no `Compile*` methods in normal `SourceCodeServices`?

I think that the API should be normalised that way, its annoying to have to create another type to Compile when you are already using `FsharpChecker` in SourceCodeServices which essentially the same API.

**Comment by dsyme** [comment]
@7sharp9 - yes, it would be reasonable to bring the Compile methods into FSharpChecker. For starters that could then help ensure the same Reactor thread is used for both checking and compilation.

**Comment by dsyme** [comment]
This fix is good enough considering it only affects the compile-from-AST methods.  

There is certainly duplication between the AST and compile-from-text paths which ideally should be resolved in the future, e.g. the command-line arguments governing the compilation (such as noframework) should probably come inn textual form, for uniformity with the rest of the compiler services.  But that would be a different commit.

So I'm ok to merge this.

**Comment by eiriktsarpalis** [comment]
Thanks. Looking forward for a nuget package update!

**Pull request merged**
