### PR TITLE
Added Fix to allow implicit PCL references to be retrieved from FSharpProjectFileInfo

### PR DESCRIPTION
**Pull request by 7sharp9**
Also added project tests for profile 7,78,259

### CODE REVIEW

**Comment by rneatherway** [comment]
I think the test project files might be missing, I get:

```
Errors and Failures:
1) Test Error : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile259 project
   System.IO.FileNotFoundException : Project file /home/robin/dev/other/FSharp.Compiler.Service/tests/service../../projects/Sample_VS2013_FSharp_Portable_Library_net451_adjusted_to_profile259/Sample_VS2013_FSharp_Portable_Library_net451.fsproj not found
Parameter name: projectFileName
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectFileInfo..ctor (System.String fsprojFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 enableLogging) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.GetProjectOptionsFromProjectFile (System.String projectFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 loadedTimeStamp) [0x00000] in <filename unknown>:0 
  at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile259 project () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

2) Test Error : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile7 project
   System.IO.FileNotFoundException : Project file /home/robin/dev/other/FSharp.Compiler.Service/tests/service../../projects/Sample_VS2013_FSharp_Portable_Library_net45/Sample_VS2013_FSharp_Portable_Library_net45.fsproj not found
Parameter name: projectFileName
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectFileInfo..ctor (System.String fsprojFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 enableLogging) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.GetProjectOptionsFromProjectFile (System.String projectFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 loadedTimeStamp) [0x00000] in <filename unknown>:0 
  at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile7 project () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

3) Test Error : FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile78 project
   System.IO.FileNotFoundException : Project file /home/robin/dev/other/FSharp.Compiler.Service/tests/service../../projects/Sample_VS2013_FSharp_Portable_Library_net451_adjusted_to_profile78/Sample_VS2013_FSharp_Portable_Library_net451.fsproj not found
Parameter name: projectFileName
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectFileInfo..ctor (System.String fsprojFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 enableLogging) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.GetProjectOptionsFromProjectFile (System.String projectFileName, Microsoft.FSharp.Core.FSharpOption`1 properties, Microsoft.FSharp.Core.FSharpOption`1 loadedTimeStamp) [0x00000] in <filename unknown>:0 
  at FSharp.Compiler.Service.Tests.ProjectOptionsTests.Project file parsing -- PCL profile78 project () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by 7sharp9** [comment]
They are part of FCS?

**Comment by 7sharp9** [comment]
The tests pass, mono has a `SIGSEGV` though in some other area.

**Comment by 7sharp9** [comment]
@rneatherway Do you need me to do anything else?  I just tested on a fresh checkout and everything tests ok.

**Comment by rneatherway** [comment]
I'll retest on a clean checkout in a few minutes.

**Comment by 7sharp9** [comment]
Ok, the appveyor tests also went through ok.

**Comment by rneatherway** [comment]
The tests pass fine for me too now. The problem above seemed to be improperly concatenated paths without a directory separator.

**Comment by rneatherway** [comment]
Just rerunning Travis to confirm it is transient, then will merge.

**Comment by rneatherway** [comment]
Some NuGet issue now....

**Comment by rneatherway** [comment]
Great! Simple but important fix. That'll help Emacs too, thanks Dave.

**Pull request merged**
